export const GET_ALL_GNOMES_START = 'GET_ALL_GNOMES_START';
export const GET_ALL_GNOMES_SUCCESS = 'GET_ALL_GNOMES';
export const GET_ALL_GNOMES_FAIL = 'GET_ALL_GNOMES_FAIL';
export const GET_ONE_GNOME_SUCCESS = 'GET_ONE_GNOME_SUCCESS';
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';